runtime: custom
env: flex
service: sormas-develop
dispat
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

resources:
  cpu: 2
  memory_gb: 4

beta_settings:
  cloud_sql_instances: onyx-yeti-271818:europe-west1:sormas-dev=tcp:5432

env_variables:
  DB_HOST: postgres
  DB_PORT: 5432
  DB_NAME: sormas_db
  DB_NAME_AUDIT: sormas_audit_db
  SORMAS_POSTGRES_PASSWORD: sormasdev
  SORMAS_POSTGRES_USER: sormas_user
  MAIL_FROM: admin@example.com