version: '2.3'
services:
  sormas:
    build: .
    ports:
    - "4848:4848"
    - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=sormas_db
      - DB_NAME_AUDIT=sormas_audit_db
      - SORMAS_POSTGRES_PASSWORD=sormas
      - SORMAS_POSTGRES_USER=sormas_user
      - MAIL_FROM=admin@example.com
    mem_limit: 2G

  postgres:
    image: hzibraunschweig/sormas-postgres:${SORMAS_DOCKER_VERSION:-2.7.2}
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    environment:
      - POSTGRES_PASSWORD=sormas
      - DB_NAME=sormas_db
      - DB_NAME_AUDIT=sormas_audit_db
      - SORMAS_POSTGRES_PASSWORD=sormas
      - SORMAS_POSTGRES_USER=sormas_user
      - TZ=Europe/Berlin
    volumes:
      - ./sormas-cargo/target/psql-payara-dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"