site_name: SORMAS
repo_name: 'hzi-braunschweig/SORMAS-Project'
repo_url: 'https://github.com/hzi-braunschweig/SORMAS-Project'

theme:
  name: material
  features:
  - tabs
extra:
  version: 0.10
  palette:
    primary: 'cyan'
  social:
  - icon: 'fontawesome/brands/github-alt'
    link: 'https://github.com/hzi-braunschweig/SORMAS-Project'
plugins:
- search:
    separator: '[\s]+'

nav:
- For Developers:
  - Automated Setup: 'DEVELOPMENT_ENVIRONMENT.md'
  - Manual Setup: 'SERVER_SETUP.md'
  - License: 'ADDING_LICENSE.md'
- For Admins:
  - 'SERVER_CUSTOMIZATION.md'
  - 'SERVER_UPDATE.md'
  - 'SOP_DISEASES.md'
- Offical Website: "https://sormas.org"