version: '2.3'
services:

  postgres:
    image: hzibraunschweig/sormas-postgres:${SORMAS_DOCKER_VERSION}
    restart: unless-stopped
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    environment:
      - POSTGRES_PASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - DB_NAME=sormas
      - DB_NAME_AUDIT=sormas_audit
      - SORMAS_POSTGRES_PASSWORD=${SORMAS_POSTGRES_PASSWORD}
      - SORMAS_POSTGRES_USER=${SORMAS_POSTGRES_USER}
      - TZ=${TZ}
    volumes:
      - ${SORMAS_PATH:-./target}/psql-payara-dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    cpus: ${DB_CPUS}
    mem_limit: ${DB_MEM:-2000m}
    mem_reservation: ${DB_MEM_RESERVED:-1000,}
    healthcheck:
      test: ["CMD", "psql", "-U", "${SORMAS_POSTGRES_USER}", "-c", "SELECT 1;", "${DB_NAME}"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
